apiVersion: v1
kind: ConfigMap
metadata:
  name: student-config
data:
  APP_NAME: "student-service"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"

  DATABASE_PRIMARY_URL: "postgres://postgres:password@172.17.0.1:5432/student_service"
  DATABASE_REPLICA_URL: "postgres://postgres:password@172.17.0.1:5432/student_service"

  DB_MAX_CONNECTIONS: "20"

  KAFKA_BROKER: "172.17.0.1:29092"
  KAFKA_TOPIC_STUDENT_EVENTS: "student-events"
  KAFKA_TOPIC_SUPERVISION_EVENTS: "supervision-events"

  REDIS_URL: "redis://172.17.0.1:6379"
  REDIS_MAX_CONNECTIONS: "10"
  REDIS_CONNECTION_TIMEOUT_SECS: "5"

  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://172.17.0.1:4317"
  OTEL_SERVICE_NAME: "student-service"
  OTEL_SERVICE_VERSION: "0.1.0"